steps:
  # 1. Construir la imagen del Gateway
  - name: 'gcr.io/cloud-builders/docker'
    dir: 'gateway'
    args:
      - 'build'
      - '-t'
      - '${_DEPLOY_REGION}-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/${_SERVICE_NAME}:${COMMIT_SHA}'
      - '.'
    id: 'Build Gateway'

  # 2. Subir la imagen del Gateway
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '${_DEPLOY_REGION}-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/${_SERVICE_NAME}:${COMMIT_SHA}'
    id: 'Push Gateway'

  # 3. Desplegar a Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE_NAME}'
      - '--image'
      - '${_DEPLOY_REGION}-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/${_SERVICE_NAME}:${COMMIT_SHA}'
      - '--region'
      - '${_DEPLOY_REGION}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'
      - '--set-env-vars'
      - 'BUCKET_NAME=manito-sessions,GEMINI_API_KEY=${_GEMINI_API_KEY}'
      - '--service-account'
      - 'whatsapp-gateway-sa@${PROJECT_ID}.iam.gserviceaccount.com'
    id: 'Deploy Gateway'

images:
  - '${_DEPLOY_REGION}-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/${_SERVICE_NAME}:${COMMIT_SHA}'

substitutions:
  _SERVICE_NAME: servidormanito
  _DEPLOY_REGION: europe-west1
  _GEMINI_API_KEY: your-gemini-api-key

options:
  logging: CLOUD_LOGGING_ONLY
