steps:
  # 1️⃣ Construir la imagen del contenedor
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - '$_DEPLOY_REGION-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/$_SERVICE_NAME:$COMMIT_SHA'
      - '.'
    id: 'Construir imagen'

  # 2️⃣ Subir la imagen al Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '$_DEPLOY_REGION-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/$_SERVICE_NAME:$COMMIT_SHA'
    id: 'Subir imagen'

  # 3️⃣ Desplegar en Cloud Run con permisos adecuados
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - '$_SERVICE_NAME'
      - '--image'
      - '$_DEPLOY_REGION-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/$_SERVICE_NAME:$COMMIT_SHA'
      - '--region'
      - '$_DEPLOY_REGION'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'PORT=8080,NODE_ENV=production,NEXTJS_APP_URL=https://studio--studio-1128284178-7d125.us-central1.hosted.app'
      - '--service-account'
      - '$_SERVICE_ACCOUNT'

images:
  - '$_DEPLOY_REGION-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/$_SERVICE_NAME:$COMMIT_SHA'

substitutions:
  _SERVICE_NAME: 'servidor-manito'
  _DEPLOY_REGION: 'us-central1'
  _SERVICE_ACCOUNT: 'cloud-run-writer@$PROJECT_ID.iam.gserviceaccount.com'
